- name: copy mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb server
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: update mongodb  listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart Mongodb
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes



















