- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed
  
- name: remove old html content
  ansible.builtin.file:  
    path: /usr/share/nginx/html
    state: absent

- name: Download front end content and extract it
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    dest: /tmp
    remote_src: yes
 
- name: copy frontend content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes
 
# - name: copy robos#hop config file
#   ansible.builtin.template:
# 	 src: roboshop.conf
#    dest: /etc/nginx/default.d/roboshop.conf

# - name: Restart Ngnix Service
#   ansible.builtin.systemd
#     state: restarted
#     name: nginx
 
 
  
